import Head from "next/head";

import Header from "../components/Header";
import HeroSection from "../components/Hero";
import ShortenLinkSection from "../components/ShortenLink";
import StatisticsSection from "../components/StatisticsSection";
import BoostLinksSection from "../components/BoostLinksSection";

/*
TODO
This project must:
- View the optimal layout for the site depending on their device's screen size
- Shorten any valid URL
- See a list of their shortened links, even after refreshing the browser
- Copy the shortened link to their clipboard in a single click
- Receive an error message when the `form` is submitted if:
  - The `input` field is empty


*/

export default function Home() {
  return (
    <>
      <Head>
        <title>Shortly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Header />

      <main>
        <HeroSection />
        <ShortenLinkSection />
      </main>

      <StatisticsSection />
      <BoostLinksSection />

      <footer>
        <div className="LOGO"></div>

        <nav></nav>

        <div className="social"></div>
      </footer>
    </>
  );
}
